In [1]:
import json
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.datasets import make_blobs
from collections import Counter


In [2]:

user_data_json = open('C:/Users/SSAFY/Desktop/21321/AB_finalpjt/back/bank/accounts/fixtures/accounts/user_data.json', encoding='UTF8')
user_data_list = json.load(user_data_json)
product_json = open('C:/Users/SSAFY/Desktop/21321/AB_finalpjt/back/bank/accounts/fixtures/accounts/depo_info_data326.json', encoding='UTF8')
product_list = json.load(product_json)



In [3]:

df = pd.DataFrame(product_list)
df_user = pd.DataFrame(user_data_list)
data = df_user[['age','gender','salary','money']]


In [6]:
kmeans = KMeans(n_clusters=4)
kmeans.fit(data)


C:\Users\SSAFY\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
C:\Users\SSAFY\anaconda3\lib\site-packages\sklearn\cluster\_kmeans.py:1382: UserWarning: KMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can avoid it by setting the environment variable OMP_NUM_THREADS=4.
  warnings.warn(


KMeans(n_clusters=4)

In [9]:



labels = kmeans.labels_
centroids = kmeans.cluster_centers_


[[5.36451613e+01 1.59274194e+00 1.12694355e+09 1.11238710e+09]
 [5.24608696e+01 1.50000000e+00 1.12863913e+09 3.58156522e+08]
 [4.64210526e+01 1.41295547e+00 3.59348178e+08 1.10245749e+09]
 [5.03927273e+01 1.46545455e+00 3.93360000e+08 3.71709091e+08]]


In [8]:

df_user['cluster_label'] = labels
print(labels)

[0 3 0 1 0 1 1 0 1 0 3 1 0 2 0 2 0 3 0 0 2 0 0 3 3 2 1 2 3 2 3 3 0 3 3 0 0
 3 0 3 3 3 1 0 3 2 0 1 0 1 0 3 2 0 2 3 2 3 0 3 3 1 0 2 2 2 0 2 2 3 2 3 2 1
 2 1 1 2 0 3 2 3 2 0 1 3 0 0 0 2 2 1 2 1 0 3 1 2 1 2 0 0 1 0 3 0 1 3 1 1 0
 1 2 2 0 0 3 0 2 1 1 3 2 3 3 2 3 2 1 0 0 3 1 3 2 1 1 3 3 1 2 0 0 2 1 0 3 2
 0 1 0 2 0 3 3 1 1 0 0 1 0 2 1 0 2 1 2 0 1 2 0 1 2 0 3 0 3 2 2 3 0 0 3 2 0
 1 0 0 1 2 3 2 3 1 1 1 0 2 2 3 2 2 2 0 3 3 2 1 2 2 1 1 0 2 0 2 3 1 0 2 0 2
 3 0 1 2 1 3 1 1 2 1 3 3 2 2 1 0 1 1 1 1 0 1 2 0 0 2 0 2 3 2 3 1 2 1 3 0 0
 3 1 1 3 1 2 3 3 2 1 0 2 1 2 2 2 2 1 2 3 1 0 2 2 3 3 3 3 1 2 0 0 3 2 0 1 2
 0 3 1 3 0 3 2 0 1 2 0 1 2 1 3 2 0 3 3 2 0 1 3 0 1 1 2 0 3 0 0 0 3 1 0 3 0
 0 2 3 3 3 3 3 3 1 2 0 1 3 1 1 2 3 1 2 0 1 2 3 3 1 1 3 2 2 0 3 1 1 1 2 1 2
 0 3 2 0 2 3 1 2 3 3 1 3 0 1 0 0 1 3 2 3 2 3 1 0 2 2 3 0 1 2 3 0 3 0 3 1 1
 2 0 3 0 3 0 0 3 0 0 1 2 3 0 3 0 0 2 2 1 0 0 2 3 1 0 2 1 1 2 1 2 3 2 3 0 3
 2 3 1 1 2 1 3 2 3 2 1 2 3 1 2 1 2 0 1 2 2 1 3 2 0 3 3 3 1 1 0 1 2 3 3 0 2
 1 0 1 1 3 1 2 0 3 0 3 3 

In [ ]:

# print(df_user['cluster_label']==1)
# 클러스터는 4으로 정했고,,  0~4까지 User가 어느구간에 속하는지 보고.
# cluster_label이 0~3 (0,1,2,3) 인 값들의 financial_products 파악하기 !!!!
cluster_products = {}
for cluster  in range(k):
  # 파악했으면 뭐가 가장 많은지 확인해야지 !!!!
  financial_products = df_user.loc[df_user['cluster_label'] == 1, 'financial_products']
  
  # 리스트를 딕셔너리로 변환하여 상품 개수 세기
  product_count = dict(Counter(list(financial_products)))

  # 딕셔너리의 key(상품)에 value(카운트) 넣어주자 
  cluster_products[cluster] = product_count


# 내가 속하는 구간어떻게구하지 ?...


# 상위 3개 출력 >> 그게 추천 (처음은 0이나옴, (상품가입을안한사람이 더 많으니까))
for product, count in cluster_products.items():
  # 개수가 많은 순서로 정렬하여 상품 순서대로 나열
  sorted_products = sorted(product_count.items(), key=lambda x: x[1], reverse=True)
  top_products = [product for product, count in sorted_products[:3]]
  cluster_products[cluster] = top_products

# 이제 출력하자
for cluster, recommended_products in cluster_products.items():
    print(f"Cluster {cluster}: {recommended_products}")

